HTML and basic JavaScript Capstone project
anasbassi/Capstone-Project-1 pull request #1
Opened 2022-06-23 16:33 UTC by anasbassi

>In this project, I built a  website for the African basketball academy, The website has mainly two pages, the home page and the about page. The home page overviews what the academy is all about with the list of available programs, coaches, and partners. 
>At the same time, the about page describes the academy in more detail. 
>The web pages were built using HTML, CSS, and JavaScript.
>The website was then hosted using Github pages.

2022-06-23 19:30 UTC, zieeco requested changes
Hi @anasbassi ,


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
_Check the comments under the review._

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 19:30 UTC, zieeco commented on README.md
- Please, kindly make the author singular as you've worked on this project alone to make your readme more professional following the [microverse readme template](https://github.com/microverseinc/readme-template) structure format..

2022-06-23 19:30 UTC, zieeco commented on README.md
> -
- Please, kindly add the contributing header and add the link to the issue page of this project to make your readme more professional following the [microverse readme template](https://github.com/microverseinc/readme-template) structure format..

2022-06-23 19:30 UTC, zieeco commented on README.md
> -## Show your support
- Please, kindly add the "Show your support" header and add the relevant content to it to make your readme more professional following the [microverse readme template](https://github.com/microverseinc/readme-template) structure format.

2022-06-23 19:30 UTC, zieeco commented on README.md
> -- etc
- [ ]  Please kindly give credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) to make your readme look more professional.

2022-06-23 19:30 UTC, zieeco commented on index.html
> +  </footer>
- Please, kindly ensure the footer on the Home and About page has the same background color of white to match the design as much as you can.

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +
- [ ] Please, kindly adjust your styling on the first nav bar by adding some space to match the design as much as you.
- [ ] Also, please add this CSS reset to remove the padding, and margin added by default to the HTML element by the browser so that your logo `AB.Academy` will not have the extra margin-top and bottom that is making your second nav grow and appearing too big compared to the original design. 

``` 
*,
*::before,
*::after {margin; 0; padding: 0; box-sizing: border-box}
```


*Original nav bar space*
![line](https://user-images.githubusercontent.com/59397159/175360767-5cc1b238-4ff8-4e3a-9bec-f1dcc9d4d01d.png)

*your nav bar space + margin-top and margin-bottom added by default*
![see](https://user-images.githubusercontent.com/59397159/175360959-35280329-5cef-49d9-9252-842549a44327.png)

*Original design*
![nospace](https://user-images.githubusercontent.com/59397159/175363043-ffd2bff5-22a8-41e5-8c77-7e649aace032.png)

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +    opacity: 0.5;
- [ ] According to the project requirement, kindly remove the opacity to make it have a white background, instead, add this opacity to the `.dropdown-icon` in your `style.css:192`

2022-06-23 19:30 UTC, zieeco commented on script.js
> +
- Please, kindly ensure you add 6 content here to match the design and to meet the project requirement as your contents now are 4, remaining 2.

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +}
**Note: this change is applicable to the content in the cards**

- [x] By default, all your content has margin and padding added to the element by the browser, after you've added the reset I told you about, it should fix the issue with your element growing unexpectedly. 
- [x] Also, do try to make your program card not too big to match the design as much as you can. 
Tips: Play around with the margin in the `.program h3`.

*your card*
![size](https://user-images.githubusercontent.com/59397159/175367160-7ed76cfb-abe1-43cb-aa9e-11105a450462.png)


*design card*
![dcard](https://user-images.githubusercontent.com/59397159/175367664-7eaf2acf-bb86-47db-aa38-4f352050c7c5.png)

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +}
- [x] Please, kindly adjust your styling on each card and its content to match the design as much as you can below:


*Design*
![psect](https://user-images.githubusercontent.com/59397159/175371365-8d4c6a23-88eb-46f7-8534-15244524062d.png)

*your design*
![psectt](https://user-images.githubusercontent.com/59397159/175371345-612fff76-9351-43d9-ad99-295cac67993b.png)

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +}
**[OPTIONAL]**

- [x] Please, also adjust the styling in your footer as your footer is too big to improve the user experience which is a great deal in responsive design.

![footer_space](https://user-images.githubusercontent.com/59397159/175373592-3441b78f-886a-4af8-a97d-69cfdfe33c5d.png)

2022-06-23 19:30 UTC, zieeco commented on index.html
> +  <title>Document</title>
- [x] Please, kindly give a name to your website to improve the SEO and web accessibility of your page.

2022-06-23 19:30 UTC, zieeco commented on index.html
> +      <a href=""><h1>AB.Academy</h1></a>
- [ ] Please, kindly add the index.htm in the `href` attribute to improve the user experience so that it takes the back to the home page.

- You can add it like this `      <a href="/"><h1>AB.Academy</h1></a>`

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +
- [ ] Please, kindly ensure the text content is aligned in the center to match the design. Add a  `text-align: center` to achieve that below:

*design text*
![text](https://user-images.githubusercontent.com/59397159/175375649-f0b6941e-61d4-455b-9f1f-60b3fbe957ba.png)

*your design text*
![yourtext](https://user-images.githubusercontent.com/59397159/175375622-cc3ac2c4-ce39-45ad-aa42-1f3c7ead9de6.png)

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +}
- [ ] Hey, I really admire your hard work on the project. I know you're meant to customize the design but let's keep in mind that we're making a clone of an existing website, so it should almost be identical to the original. I think the added image here is not necessary, following the design format. In order to maintain the design format, the image shouldn't be added but could be replaced with the logo. 
Please, kindly fix this issue. :pray: 

![aded_image](https://user-images.githubusercontent.com/59397159/175377415-b87018e2-aac3-426f-a215-03bb8463e39a.png)

2022-06-23 19:30 UTC, zieeco commented on about.html
> +  <title>Document</title>
- [ ] Please, kindly give a name to your website to improve the SEO and web accessibility of your page.

2022-06-23 19:30 UTC, zieeco commented on about.html
> +      <a href=""><h1>AB.Academy</h1></a>
- [ ] Please, kindly add an opacity of 0.5 to the logo to match the design color to make it have a good feel and look to improve the user experience.
![see](https://user-images.githubusercontent.com/59397159/175378803-6159cbf7-c881-4926-9f14-a219b92b37c1.png)


![se](https://user-images.githubusercontent.com/59397159/175378769-dc8ee0e3-bbd5-46b8-a829-e69e5ebf3774.png)

2022-06-23 19:30 UTC, zieeco commented on about.html
> +      <a href=""><h1>AB.Academy</h1></a>
- [ ] Please, kindly add an opacity of 0.5 to the logo to match the design color to make it have a good feel and look to improve the user experience.


![se](https://user-images.githubusercontent.com/59397159/175378769-dc8ee0e3-bbd5-46b8-a829-e69e5ebf3774.png)

![feel](https://user-images.githubusercontent.com/59397159/175380433-cc745e90-613a-416d-9c89-ed6fe320038a.png)

2022-06-23 19:30 UTC, zieeco commented on css/styles.css
> +}
- Please, kindly adjust your styling on the desktop version so that it matches the design as much as you can. 
- [x] Esure the text content are not moving down too much above the image.
- [x] Reduce the font-size.
- [x] Reduce the font-weight.

*Design*
![desk](https://user-images.githubusercontent.com/59397159/175381131-5a9d2beb-e37f-4bc0-8fea-aead726c02e4.png)

*your design*
![deskcon](https://user-images.githubusercontent.com/59397159/175381101-05d8233c-bd6a-4fd0-8c0f-2b3cfe6225e2.png)

2022-06-23 20:36 UTC, anasbassi commented on index.html
> +  </footer>
hello @zieeco
Thank you for the feedback the footer according to the design for the about page is different from that of the home page, do you still recommend I change it to white?
![home-footer](https://user-images.githubusercontent.com/92439670/175394709-7480a557-744f-45b5-8ede-b7daf0f7d9d3.PNG)
![about-footer](https://user-images.githubusercontent.com/92439670/175394726-66461345-a553-471d-b767-d346202f40e5.PNG)
.

2022-06-24 15:34 UTC, ShahierNashaat approved these changes
Hi @anasbassi , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-24 16:51 UTC, merged